In [10]:
import tiktoken
import os
import torch

In [7]:
# get all the unique characters that occur in this text
chars = ["A", "B", "-", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "[", "]", "(", ")", "{", "}", ",", ".", ":"]
vocab_size = len(chars)
print("all the unique characters:", ''.join(chars))
print(f"vocab size: {vocab_size:,}")

all the unique characters: AB-0123456789[](){},.:
vocab size: 22


In [8]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
def encode(s):
    return [stoi[c] for c in s] # encoder: take a string, output a list of integers
def decode(l):
    return ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

In [9]:
data_folder = "/home/user/Documents/projects/robosuite-notebooks/datagen/manuals_01"
input_file_path = os.path.join(data_folder, "captions.txt")
output_file_path = os.path.join(data_folder, "captions_tokenized.tar")

In [13]:
captions_tokenized = torch.load(output_file_path)

In [18]:
captions_tokenized

tensor([[ 0, 21, 17,  ..., 14, 18, 20],
        [ 0, 21, 17,  ..., 14, 18, 20],
        [ 0, 21, 17,  ..., 14, 18, 20],
        ...,
        [ 0, 21, 17,  ..., 14, 18, 20],
        [ 0, 21, 17,  ..., 14, 18, 20],
        [ 0, 21, 17,  ..., 14, 18, 20]], dtype=torch.uint8)

In [24]:
with open(input_file_path, 'r') as f:
    data = f.read()
data = data.replace(" ", "").split("\n")
data[0]

'A:{0:[1,2],1:[1,4],2:[2,3],3:[3,4],4:[2,3],5:[1,4],6:[3,4]}.'

In [26]:
a = encode(data[0])
print(a)

[0, 21, 17, 3, 21, 13, 4, 19, 5, 14, 19, 4, 21, 13, 4, 19, 7, 14, 19, 5, 21, 13, 5, 19, 6, 14, 19, 6, 21, 13, 6, 19, 7, 14, 19, 7, 21, 13, 5, 19, 6, 14, 19, 8, 21, 13, 4, 19, 7, 14, 19, 9, 21, 13, 6, 19, 7, 14, 18, 20]


In [35]:
decode(a)

'A:{0:[1,2],1:[1,4],2:[2,3],3:[3,4],4:[2,3],5:[1,4],6:[3,4]}.'

In [34]:
len(a)


60

In [1]:
import torch

In [2]:
a = torch.Tensor([1, 2, 3]).type(torch.uint8)
a

tensor([1, 2, 3], dtype=torch.uint8)

In [3]:
torch.save(a, "test.tar")

In [4]:
torch.load("test.tar")

tensor([1, 2, 3], dtype=torch.uint8)